Projects/11/11-1/Guestbook/Models/Guestbooks.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guestbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guestbooks
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Reply { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
    }
}

Projects/11/11-1/Guestbook/ViewModels/GuestbookView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Guestbook.Models;
using System.ComponentModel;
using Guestbook.Services;

namespace Guestbook.ViewModels
{
    public class GuestbookView
    {
        //搜尋欄位
        [DisplayName("搜尋：")]
        public string Search { get; set; }
        //顯示資料陣列
        public List<Guestbooks> DataList { get; set; }
        //分頁內容
        public ForPaging Paging { get; set; }
    }
}

Projects/11/11-1/Guestbook/Controllers/GuestbookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Guestbook.Models;
using Guestbook.Services;
using Guestbook.ViewModels;

namespace Guestbook.Controllers
{
    public class GuestbookController : Controller
    {
        //宣告Guestbooks資料表的Service物件
        GuestbooksDBService guestbookService = new GuestbooksDBService();



       //起始頁面
        public ActionResult Index()
        {
            return View();
        }

        //取得資料陣列用Action，將Page(頁數)預設為1
        public ActionResult GetDataList(string Search, int Page = 1)
        {
            //宣告一個新頁面模型
            GuestbookView Data = new GuestbookView();
            //將傳入值Search(搜尋)放入頁面模型中
            Data.Search = Search;
            //新增頁面模型中的分頁
            Data.Paging = new ForPaging(Page);
            //從Service中取得頁面所需陣列資料
            Data.DataList = guestbookService.GetDataList(Data.Paging, Data.Search);
            //將頁面資料傳入View中
            return PartialView(Data);
        }

        [HttpPost] //設定搜尋為接受頁面POST傳入
        //使用Bind的Inculde來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult GetDataList([Bind(Include = "Search")]GuestbookView Data)
        {
            //重新導向頁面至開始頁面，並傳入搜尋值
            return RedirectToAction("GetDataList", new { Search = Data.Search });
        }


        #region 新增留言
        //新增留言一開始載入頁面
        public ActionResult Create()
        {
            //因此頁面用於載入至開始頁面中，故使用部分檢視回傳
            return PartialView();
        }
        //新增留言傳入資料時的Action
        [HttpPost] //設定此Action只接受頁面POST資料傳入
        //使用Bind的Include來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult Add([Bind(Include = "Name,Content")]Guestbooks Data)
        {
            //使用Service來新增一筆資料
            guestbookService.InsertGuestbooks(Data);
            //重新導向頁面至開始頁面
            return RedirectToAction("Index");
        }
        #endregion

        #region 修改留言
        //修改留言頁面要根據傳入編號來決定要修改的資料
        public ActionResult Edit(int Id)
        {
            //取得頁面所需資料，藉由Service取得
            Guestbooks Data = guestbookService.GetDataById(Id);
            //將資料傳入View中
            return View(Data);
        }

        //修改留言傳入資料時的Action
        [HttpPost] //設定此Action只接受頁面POST資料傳入
        //使用Bind的Inculde來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult Edit(int Id, [Bind(Include = "Name,Content")]Guestbooks UpdateData)
        {
            //修改資料的是否可修改判斷
            if (guestbookService.CheckUpdate(Id))
            {
                //將編號設定至修改資料中
                UpdateData.Id = Id;
                //使用Service來修改資料
                guestbookService.UpdateGuestbooks(UpdateData);
                //重新導向頁面至開始頁面
                return RedirectToAction("Index");
            }
            else
            {
                //重新導向頁面至開始頁面
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region 回覆留言
        //回覆留言頁面要根據傳入編號來決定要回覆的資料
        public ActionResult Reply(int Id)
        {
            //取得頁面所需資料，藉由Service取得
            Guestbooks Data = guestbookService.GetDataById(Id);
            //將資料傳入View中
            return View(Data);
        }

        //修改留言傳入資料時的Action
        [HttpPost] //設定此Action只接受頁面POST資料傳入
        //使用Bind的Inculde來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult Reply(int Id, [Bind(Include = "Reply,ReplyTime")]Guestbooks ReplyData)
        {
            //修改資料的是否可修改判斷
            if (guestbookService.CheckUpdate(Id))
            {
                //將編號設定至回覆留言資料中
                ReplyData.Id = Id;
                //使用Service來回覆留言資料
                guestbookService.ReplyGuestbooks(ReplyData);
                //重新導向頁面至開始頁面
                return RedirectToAction("Index");
            }
            else
            {
                //重新導向頁面至開始頁面
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region 刪除留言
        //刪除頁面要根據傳入編號來刪除資料
        public ActionResult Delete(int Id)
        {
            //使用Service來刪除資料
            guestbookService.DeleteGuestbooks(Id);
            //重新導向頁面至開始頁面
            return RedirectToAction("Index");
        }
        #endregion

       

    }
}

Projects/11/11-1/Guestbook/Views/Guestbook/Create.cshtml
@model Guestbook.Models.Guestbooks
@*建立新增資料所須的表單*@
@using (Html.BeginForm("Add", "Guestbook"))
{
    <h3>新增留言</h3>
    <table>
        @*新增姓名欄位區塊*@
        <tr>
            <td>
                @Html.LabelFor(model => model.Name)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </td>
        </tr>
        @*新增內容欄位區塊*@
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </td>
        </tr>
    </table>
    <input type="submit" value="新增留言" />
}

Projects/11/11-1/Guestbook/Views/Guestbook/Edit.cshtml
@model Guestbook.Models.Guestbooks

@{
    ViewBag.Title = "修改留言";
}
@*匯入驗證欄位所須的JavaScript*@
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval.js")
}
@*建立修改欄位所須的表單*@
@using (Html.BeginForm())
{
    <h3>修改留言</h3>
    @*建立修改留言表格*@
    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Name)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </td>
        </tr>
    </table>
    @*判斷是否有人回覆，如果無人回覆，即可修改，否則不可修改*@
    if (Model.ReplyTime == null)
    {
        <input type="submit" value="修改留言" />
    }
    else
    {
        <text>此留言已回覆無法修改，請</text>
        @Html.ActionLink("返回列表", "Index")
    }
}

Projects/11/11-1/Guestbook/Views/Guestbook/GetDataList.cshtml
@model Guestbook.ViewModels.GuestbookView

<div id="DataList">
    <h3>留言板內容</h3>
    @*建立搜尋所須的表單(使用AjaxHelper，並設定取代Id為DataList部分)*@
    @using (Ajax.BeginForm("DataList", "Guestbook"
    , new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace
        ,
        UpdateTargetId = "DataList"
    }))
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Search)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Search)
                </td>
                <td>
                    <input type="submit" value="搜尋" />
                </td>
            </tr>
        </table>
    }
    <table>
        @*如果資料庫中不是零筆記錄，則顯示資料，並列出新增、刪除與修改連結*@
        @if (!Model.DataList.Count.Equals(0))
        {
            foreach (var item in Model.DataList)
            {
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Name)
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].CreateTime)
                    </td>
                    <td>
                        @item.CreateTime
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Content)
                    </td>
                    <td colspan="3">
                        @item.Content
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Reply)
                    </td>
                    <td colspan="3">
                        @item.Reply
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].ReplyTime)
                    </td>
                    <td>
                        @item.ReplyTime
                    </td>
                    <td colspan="2">
                        @Html.ActionLink("修改留言", "Edit", new { Id = item.Id })
                        @Html.ActionLink("回覆留言", "Reply", new { Id = item.Id })
                        @Html.ActionLink("刪除留言", "Delete", new { Id = item.Id })
                    </td>
                </tr>
            }
        }
        @*如果資料庫中為零筆記錄，則印出"資料庫內查無資料"*@
        else
        {
            <tr>
                <td colspan="4">
                    資料庫內查無資料
                </td>
            </tr>
        }
        @*顯示頁數連結(使用AjaxHelper，並設定取代Id為DataList部分)*@
        <tr>
            <td>
                @*若目前所在頁數大於1，則顯示上一頁與最前頁的按鈕*@
                @if (Model.Paging.NowPage > 1)
                {
                    @Ajax.ActionLink("<<", "Index"
                    , new { Page = 1, Search = Model.Search }
                        , new AjaxOptions
                        {
                            InsertionMode = InsertionMode.Replace
                            ,
                            UpdateTargetId = "DataList"
                        })
                    @Ajax.ActionLink("<", "Index"
                    , new { Page = Model.Paging.NowPage - 1, Search = Model.Search }
                        , new AjaxOptions
                        {
                            InsertionMode = InsertionMode.Replace
                            ,
                            UpdateTargetId = "DataList"
                        })
                }
            </td>
            <td>
                @*顯示當前頁數前後各五頁的頁數*@
                @for (var page = (Model.Paging.NowPage - 6);
                page < (Model.Paging.NowPage + 6); page++)
                {
                    if ((page > 0) && (page <= Model.Paging.MaxPage))
                    {
                        if (page == Model.Paging.NowPage)
                        {
                            <b>@page</b>
                        }
                        else
                        {
                            @Ajax.ActionLink(page.ToString(), "Index"
                            , new { Page = page, Search = Model.Search }
                                , new AjaxOptions
                                {
                                    InsertionMode =
                                        InsertionMode.Replace
                                    ,
                                    UpdateTargetId = "DataList"
                                })
                        }
                    }
                }
            </td>
            <td>
                @*若目前所在頁數小於總頁數，則顯示下一頁與最後一頁的按鈕*@
                @if (Model.Paging.NowPage < Model.Paging.MaxPage)
                {
                    @Ajax.ActionLink(">", "Index"
                    , new { Page = Model.Paging.NowPage + 1, Search = Model.Search }
                        , new AjaxOptions
                        {
                            InsertionMode = InsertionMode.Replace
                            ,
                            UpdateTargetId = "DataList"
                        })
                    @Ajax.ActionLink(">>", "Index"
                    , new { Page = Model.Paging.MaxPage, Search = Model.Search }
                        , new AjaxOptions
                        {
                            InsertionMode = InsertionMode.Replace
                            ,
                            UpdateTargetId = "DataList"
                        })
                }
            </td>
        </tr>
    </table>
</div>

Projects/11/11-1/Guestbook/Views/Guestbook/Index.cshtml
@model Guestbook.ViewModels.GuestbookView

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@Html.AntiForgeryToken()

@*載入新增留言頁面*@
<div id="CreateDate">
    @Html.Action("Create")
</div>

@*載入資料陣列頁面*@
@Html.Action("GetDataList")


@*匯入驗證欄位所須的JavaScript*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projects/11/11-1/Guestbook/Views/Guestbook/Reply.cshtml
@model Guestbook.Models.Guestbooks

@{
    ViewBag.Title = "回覆留言";
}
@*匯入驗證所須的JavaScript*@
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval.js")
}
@*建立回覆留言所須的表單*@
@using (Html.BeginForm())
{
    <h3>回覆留言</h3>
    @*建立回覆內容表格*@
    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Name)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Reply)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Reply)
                @Html.ValidationMessageFor(model => model.Reply)
            </td>
        </tr>
    </table>
    @*一則留言僅可回覆一次，若被回覆，則顯示返回列表連結*@
    if (Model.ReplyTime == null)
    {
        <input type="submit" value="回覆留言" />
    }
    else
    {
        <text>此留言已回覆，請</text>
        @Html.ActionLink("返回列表", "Index")
    }
}